const
depb=w=>(console.log(w),[...{[Symbol.iterator]:(
	p=0,
	state=0,
	head,
	val=_=>[...{[Symbol.iterator]:d=>({next:_=>({done:d,value:d||(d=!(w[p]&0x80),w[p++]&0x7f)})})}].reduce((a,x,i)=>x<<(7*i)|a)
)=>({next:_=>w.length<=p?{done:1}:{value:(
	(([i,x])=>({i,type:x,value:[
		_=>val(),
		_=>w.slice(p,p+=8),
		(l=val())=>w.slice(p,p+=l),
		_=>_,
		_=>_,
		_=>w.slice(p,p+=4),
	][x]()}))((x=>[x>>>3,x&7])(val()))
)}})}]),
enpb=1;

export{depb,enpb};
